export type SettingType = "boolean" | "number" | "string";
export type SettingTier = "basic" | "advanced";
export type SettingCategory =
  | "feature_flag"
  | "economics"
  | "booster"
  | "ai"
  | "rate_limit"
  | "runtime"
  | "limits";

// Render order on /admin/settings. Basic categories render expanded; advanced
// collapse behind a single disclosure.
export const CATEGORY_ORDER = [
  "feature_flag",
  "economics",
  "booster",
  "ai",
  "rate_limit",
  "runtime",
  "limits",
] as const satisfies readonly SettingCategory[];

export const CATEGORY_TIER: Record<SettingCategory, SettingTier> = {
  feature_flag: "basic",
  economics: "basic",
  booster: "basic",
  ai: "advanced",
  rate_limit: "advanced",
  runtime: "advanced",
  limits: "advanced",
};

export type ConfigEntry = {
  key: string;
  category: SettingCategory;
  type: SettingType;
  label: string;
  fallback: boolean | number | string;
  tier: SettingTier;
  // Canonical env var name. Omitted when the setting has no env equivalent.
  // This is the single source of truth for key→env mapping; nothing derives
  // an env name by string transformation.
  env?: string;
  // Inclusive bounds, numbers only. Enforced on write by the admin PUT handler
  // and mirrored by the consumer's own read-side clamp.
  min?: number;
  max?: number;
  // True when the value is read once at process start, so a change needs a
  // restart to take effect. Surfaced as a badge in the admin UI.
  requiresRestart?: boolean;
};

// Source of truth for DB-overridable, non-secret config. Adding a setting
// later = one entry here; it auto-appears in the admin Settings UI. Secrets
// (API keys, credentials) NEVER appear here — they stay in .env.
export const APP_SETTINGS: ConfigEntry[] = [
  // feature_flag
  {
    key: "feature.waitlist_enabled",
    category: "feature_flag",
    tier: "basic",
    type: "boolean",
    label: "Waitlist onboarding gate",
    fallback: true,
    env: "WAITLIST_ENABLED",
  },
  {
    key: "feature.generated_build_execution",
    category: "feature_flag",
    tier: "basic",
    type: "boolean",
    label: "Generated build execution",
    fallback: false,
    env: "GENERATED_BUILD_EXECUTION_ENABLED",
  },
  {
    key: "feature.generated_public_execution",
    category: "feature_flag",
    tier: "basic",
    type: "boolean",
    label: "Generated public execution",
    fallback: false,
    env: "GENERATED_PUBLIC_EXECUTION_ENABLED",
  },
  {
    key: "feature.streamer_mode",
    category: "feature_flag",
    tier: "basic",
    type: "boolean",
    label: "Streamer mode (mask PII in admin)",
    fallback: true,
  },
  // economics
  {
    key: "economics.project_limit",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Batas proyek per pengguna",
    fallback: 5,
    env: "PROJECT_LIMIT",
    min: 1,
    max: 100,
  },
  {
    key: "economics.daily_energy_limit",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi harian gratis",
    fallback: 250000,
    min: 10000,
    max: 5000000,
  },
  {
    key: "economics.min_energy_discuss",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi minimum — diskusi",
    fallback: 5000,
    min: 0,
    max: 100000,
  },
  {
    key: "economics.min_energy_build",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi minimum — build",
    fallback: 40000,
    min: 0,
    max: 500000,
  },
  {
    key: "economics.min_energy_edit",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi minimum — edit",
    fallback: 10000,
    min: 0,
    max: 200000,
  },
  {
    key: "economics.min_energy_moderation",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi minimum — moderasi",
    fallback: 500,
    min: 0,
    max: 50000,
  },
  {
    key: "economics.micro_usd_per_energy",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Micro-USD per energi",
    fallback: 1000000,
    min: 1000,
    max: 100000000,
  },
  // booster (fallbacks mirror BOOSTER_PACKS in pakasir.ts)
  {
    key: "booster.pocket.amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Pocket — amount (Rp)",
    fallback: 2900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.pocket.energy",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Pocket — energy",
    fallback: 50000,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.starter.amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Starter — amount (Rp)",
    fallback: 8900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.starter.energy",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Starter — energy",
    fallback: 200000,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.popular.amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Popular — amount (Rp)",
    fallback: 24900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.popular.energy",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Popular — energy",
    fallback: 600000,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.max.amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Max — amount (Rp)",
    fallback: 59900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.max.energy",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Max — energy",
    fallback: 1500000,
    min: 0,
    max: 100_000_000,
  },
  // rate_limit (fallbacks mirror rate-limit.ts defaults)
  {
    key: "ratelimit.global_ip.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Global IP — requests",
    fallback: 300,
    env: "RATE_LIMIT_GLOBAL_IP_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.global_ip.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Global IP — window (s)",
    fallback: 60,
    env: "RATE_LIMIT_GLOBAL_IP_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  {
    key: "ratelimit.ai_user.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "AI user — requests",
    fallback: 60,
    env: "RATE_LIMIT_AI_USER_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.ai_user.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "AI user — window (s)",
    fallback: 600,
    env: "RATE_LIMIT_AI_USER_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  {
    key: "ratelimit.ai_ip.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "AI IP — requests",
    fallback: 20,
    env: "RATE_LIMIT_AI_IP_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.ai_ip.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "AI IP — window (s)",
    fallback: 600,
    env: "RATE_LIMIT_AI_IP_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  {
    key: "ratelimit.build_user.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Build user — requests",
    fallback: 10,
    env: "RATE_LIMIT_BUILD_USER_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.build_user.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Build user — window (s)",
    fallback: 3600,
    env: "RATE_LIMIT_BUILD_USER_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  {
    key: "ratelimit.build_ip.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Build IP — requests",
    fallback: 5,
    env: "RATE_LIMIT_BUILD_IP_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.build_ip.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Build IP — window (s)",
    fallback: 3600,
    env: "RATE_LIMIT_BUILD_IP_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  // ai (optional — tunable live)
  {
    key: "ai.timeout.moderation_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — moderation timeout (ms)",
    fallback: 30000,
    env: "AI_TIMEOUT_MODERATION_MS",
    min: 30000,
    max: 60000,
  },
  {
    key: "ai.timeout.discuss_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — discuss timeout (ms)",
    fallback: 90000,
    env: "AI_TIMEOUT_DISCUSS_MS",
    min: 30000,
    max: 180000,
  },
  {
    key: "ai.models_default",
    category: "ai",
    tier: "advanced",
    type: "string",
    label: "AI — default model id",
    fallback: "umkmcepat-combo",
    env: "AI_MODELS",
  },
  {
    key: "ai.timeout.discuss_card_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — discuss card timeout (ms)",
    fallback: 45000,
    env: "AI_TIMEOUT_DISCUSS_CARD_MS",
    min: 3000,
    max: 120000,
  },
  {
    key: "ai.timeout.discuss_one_call_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — discuss one-call timeout (ms)",
    fallback: 120000,
    env: "AI_TIMEOUT_DISCUSS_ONE_CALL_MS",
    min: 30000,
    max: 240000,
  },
  {
    key: "ai.timeout.discuss_tool_settle_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — discuss tool settle timeout (ms)",
    fallback: 30000,
    env: "AI_TIMEOUT_DISCUSS_TOOL_SETTLE_MS",
    min: 30000,
    max: 60000,
  },
  {
    key: "ai.timeout.chat_compaction_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — chat compaction timeout (ms)",
    fallback: 60000,
    env: "AI_TIMEOUT_CHAT_COMPACTION_MS",
    min: 30000,
    max: 120000,
  },
  {
    key: "ai.timeout.build_spec_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — build spec timeout (ms)",
    fallback: 120000,
    env: "AI_TIMEOUT_BUILD_SPEC_MS",
    min: 30000,
    max: 240000,
  },
  {
    key: "ai.timeout.source_generation_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — source generation timeout (ms)",
    fallback: 600000,
    env: "AI_TIMEOUT_SOURCE_GENERATION_MS",
    min: 120000,
    max: 600000,
  },
  {
    key: "ai.timeout.edit_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — edit timeout (ms)",
    fallback: 600000,
    env: "AI_TIMEOUT_EDIT_MS",
    min: 60000,
    max: 600000,
  },
  {
    key: "ai.timeout.edit_repair_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — edit repair timeout (ms)",
    fallback: 300000,
    env: "AI_TIMEOUT_EDIT_REPAIR_MS",
    min: 60000,
    max: 600000,
  },
  {
    key: "ai.agent.generate_max_steps",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — generate agent max steps",
    fallback: 30,
    env: "AI_AGENT_GENERATE_MAX_STEPS",
    min: 15,
    max: 60,
  },
  {
    key: "ai.agent.repair_max_steps",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — repair agent max steps",
    fallback: 12,
    env: "AI_AGENT_REPAIR_MAX_STEPS",
    min: 4,
    max: 40,
  },
  {
    key: "ai.agent.subagent_max_steps",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — subagent max steps",
    fallback: 8,
    env: "AI_AGENT_SUBAGENT_MAX_STEPS",
    min: 2,
    max: 15,
  },
  {
    key: "ai.generation_model",
    category: "ai",
    tier: "advanced",
    type: "string",
    label: "AI — build pipeline model id",
    fallback: "",
    env: "AI_GENERATION_MODEL",
  },
];

export function findConfigEntry(key: string): ConfigEntry | undefined {
  return APP_SETTINGS.find((e) => e.key === key);
}
