export type SettingType = "boolean" | "number" | "string";
export type SettingTier = "basic" | "advanced";
export type SettingCategory =
  | "feature_flag"
  | "economics"
  | "booster"
  | "ai"
  | "rate_limit"
  | "runtime"
  | "limits";

// Render order on /admin/settings. Basic categories render expanded; advanced
// collapse behind a single disclosure.
export const CATEGORY_ORDER = [
  "feature_flag",
  "economics",
  "booster",
  "ai",
  "rate_limit",
  "runtime",
  "limits",
] as const satisfies readonly SettingCategory[];

export const CATEGORY_TIER: Record<SettingCategory, SettingTier> = {
  feature_flag: "basic",
  economics: "basic",
  booster: "basic",
  ai: "advanced",
  rate_limit: "advanced",
  runtime: "advanced",
  limits: "advanced",
};

export type ConfigEntry = {
  key: string;
  category: SettingCategory;
  type: SettingType;
  label: string;
  fallback: boolean | number | string;
  tier: SettingTier;
  // Canonical env var name. Omitted when the setting has no env equivalent.
  // This is the single source of truth for key→env mapping; nothing derives
  // an env name by string transformation.
  env?: string;
  // Inclusive bounds, numbers only. Enforced on write by the admin PUT handler
  // and mirrored by the consumer's own read-side clamp.
  min?: number;
  max?: number;
  // True when the value is read once at process start, so a change needs a
  // restart to take effect. Surfaced as a badge in the admin UI.
  requiresRestart?: boolean;
  // When set, /admin/settings renders a select populated from this source
  // instead of a free-text input. Values remain plain strings in DB.
  optionsSource?: "nine_router_models";
  // When set, /admin/settings renders a fixed-option select (enum). Mutually
  // exclusive with optionsSource.
  enumOptions?: readonly string[];
};

// Source of truth for DB-overridable, non-secret config. Adding a setting
// later = one entry here; it auto-appears in the admin Settings UI. Secrets
// (API keys, credentials) NEVER appear here — they stay in .env.
export const APP_SETTINGS: ConfigEntry[] = [
  // feature_flag
  {
    key: "feature.waitlist_enabled",
    category: "feature_flag",
    tier: "basic",
    type: "boolean",
    label: "Waitlist onboarding gate",
    fallback: true,
    env: "WAITLIST_ENABLED",
  },
  {
    key: "feature.streamer_mode",
    category: "feature_flag",
    tier: "basic",
    type: "boolean",
    label: "Streamer mode (mask PII in admin)",
    fallback: true,
  },
  {
    key: "feature.composer_uploads_enabled",
    category: "feature_flag",
    tier: "basic",
    type: "boolean",
    label: "Composer image uploads",
    fallback: true,
  },
  {
    key: "feature.direct_edit_enabled",
    category: "feature_flag",
    tier: "basic",
    type: "boolean",
    label: "Workspace Ubah (element edit) mode",
    fallback: true,
  },
  // economics
  {
    key: "economics.project_limit",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Batas proyek per pengguna",
    fallback: 5,
    env: "PROJECT_LIMIT",
    min: 1,
    max: 100,
  },
  {
    key: "economics.signup_energy_grant",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi awal pengguna",
    fallback: 500000,
    min: 10000,
    max: 5000000,
  },
  {
    key: "economics.min_energy_discuss",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi minimum — diskusi",
    fallback: 5000,
    min: 0,
    max: 100000,
  },
  {
    key: "economics.min_energy_build",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi minimum — build",
    fallback: 40000,
    min: 0,
    max: 500000,
  },
  {
    key: "economics.min_energy_edit",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi minimum — edit",
    fallback: 10000,
    min: 0,
    max: 200000,
  },
  {
    key: "economics.min_energy_moderation",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi minimum — moderasi",
    fallback: 500,
    min: 0,
    max: 50000,
  },
  {
    key: "economics.micro_usd_per_energy",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Micro-USD per energi",
    fallback: 1000000,
    min: 1000,
    max: 100000000,
  },
  // booster (fallbacks mirror BOOSTER_PACKS in mayar.ts)
  // amount = charged price; compare_at_amount = list price for discount UI only
  {
    key: "booster.pocket.amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Pocket — harga jual (Rp)",
    fallback: 2900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.pocket.compare_at_amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Pocket — harga coret (Rp)",
    fallback: 15000,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.pocket.energy",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Pocket — energy",
    fallback: 50000,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.starter.amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Starter — harga jual (Rp)",
    fallback: 8900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.starter.compare_at_amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Starter — harga coret (Rp)",
    fallback: 45000,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.starter.energy",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Starter — energy",
    fallback: 200000,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.popular.amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Popular — harga jual (Rp)",
    fallback: 24900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.popular.compare_at_amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Popular — harga coret (Rp)",
    fallback: 125000,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.popular.energy",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Popular — energy",
    fallback: 600000,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.max.amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Max — harga jual (Rp)",
    fallback: 59900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.max.compare_at_amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Max — harga coret (Rp)",
    fallback: 299000,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.max.energy",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Max — energy",
    fallback: 1500000,
    min: 0,
    max: 100_000_000,
  },
  // rate_limit (fallbacks mirror rate-limit.ts defaults)
  {
    key: "ratelimit.global_ip.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Global IP — requests",
    fallback: 300,
    env: "RATE_LIMIT_GLOBAL_IP_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.global_ip.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Global IP — window (s)",
    fallback: 60,
    env: "RATE_LIMIT_GLOBAL_IP_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  {
    key: "ratelimit.ai_user.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "AI user — requests",
    fallback: 60,
    env: "RATE_LIMIT_AI_USER_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.ai_user.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "AI user — window (s)",
    fallback: 600,
    env: "RATE_LIMIT_AI_USER_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  {
    key: "ratelimit.ai_ip.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "AI IP — requests",
    fallback: 20,
    env: "RATE_LIMIT_AI_IP_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.ai_ip.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "AI IP — window (s)",
    fallback: 600,
    env: "RATE_LIMIT_AI_IP_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  {
    key: "ratelimit.build_user.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Build user — requests",
    fallback: 10,
    env: "RATE_LIMIT_BUILD_USER_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.build_user.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Build user — window (s)",
    fallback: 3600,
    env: "RATE_LIMIT_BUILD_USER_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  {
    key: "ratelimit.build_ip.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Build IP — requests",
    fallback: 5,
    env: "RATE_LIMIT_BUILD_IP_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.build_ip.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Build IP — window (s)",
    fallback: 3600,
    env: "RATE_LIMIT_BUILD_IP_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  {
    key: "discuss.chat.auto_retry_attempts",
    category: "feature_flag",
    tier: "advanced",
    type: "number",
    label: "Discuss chat auto-retry attempts",
    fallback: 2,
    min: 0,
    max: 5,
    env: "DISCUSS_CHAT_AUTO_RETRY_ATTEMPTS",
  },
  {
    key: "discuss.partial_tool_streaming",
    category: "feature_flag",
    tier: "advanced",
    type: "boolean",
    label: "Discuss partial tool streaming",
    fallback: true,
    env: "DISCUSS_PARTIAL_TOOL_STREAMING",
  },
  {
    key: "discuss.parallel_moderation",
    category: "feature_flag",
    tier: "advanced",
    type: "boolean",
    label: "Discuss parallel moderation (stream before verdict)",
    fallback: false,
    env: "DISCUSS_PARALLEL_MODERATION",
  },
  {
    key: "feature.thumbnail_capture_enabled",
    category: "feature_flag",
    tier: "advanced",
    type: "boolean",
    label: "Thumbnail capture",
    fallback: true,
    env: "PROJECT_THUMBNAIL_CAPTURE_ENABLED",
  },
  // runtime
  {
    key: "runtime.build_concurrency",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — build concurrency",
    fallback: 3,
    env: "PROJECT_BUILD_CONCURRENCY",
    min: 1,
    max: 16,
  },
  {
    key: "runtime.max_containers",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — max containers",
    fallback: 8,
    env: "PROJECT_RUNTIME_MAX_CONTAINERS",
    min: 1,
    max: 64,
  },
  {
    key: "runtime.health_timeout_ms",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — health timeout (ms)",
    fallback: 2000,
    env: "PROJECT_RUNTIME_HEALTH_TIMEOUT_MS",
    min: 500,
    max: 5000,
  },
  {
    key: "runtime.proxy_timeout_ms",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — proxy timeout (ms)",
    fallback: 15000,
    env: "PROJECT_RUNTIME_PROXY_TIMEOUT_MS",
    min: 1000,
    max: 30000,
  },
  {
    key: "runtime.preview_token_ttl_seconds",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — preview token TTL (s)",
    fallback: 300,
    env: "PREVIEW_ASSET_TOKEN_TTL_SECONDS",
    min: 60,
    max: 900,
  },
  {
    key: "runtime.thumbnail_concurrency",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — thumbnail concurrency",
    fallback: 1,
    env: "PROJECT_THUMBNAIL_CONCURRENCY",
    min: 1,
    max: 8,
  },
  {
    key: "runtime.thumbnail_timeout_ms",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — thumbnail timeout (ms)",
    fallback: 15000,
    env: "PROJECT_THUMBNAIL_TIMEOUT_MS",
    min: 1000,
    max: 120000,
  },
  // limits
  {
    key: "limits.source.max_files",
    category: "limits",
    tier: "advanced",
    type: "number",
    label: "Limit — source max files",
    fallback: 100,
    env: "PROJECT_SOURCE_MAX_FILES",
    min: 10,
    max: 500,
  },
  {
    key: "limits.source.max_file_bytes",
    category: "limits",
    tier: "advanced",
    type: "number",
    label: "Limit — source max file bytes",
    fallback: 262144,
    env: "PROJECT_SOURCE_MAX_FILE_BYTES",
    min: 16384,
    max: 1048576,
  },
  {
    key: "limits.source.max_total_bytes",
    category: "limits",
    tier: "advanced",
    type: "number",
    label: "Limit — source max total bytes",
    fallback: 5242880,
    env: "PROJECT_SOURCE_MAX_TOTAL_BYTES",
    min: 262144,
    max: 20971520,
  },
  {
    key: "limits.dist.max_files",
    category: "limits",
    tier: "advanced",
    type: "number",
    label: "Limit — dist max files",
    fallback: 500,
    env: "PROJECT_DIST_MAX_FILES",
    min: 10,
    max: 2000,
  },
  {
    key: "limits.dist.max_file_bytes",
    category: "limits",
    tier: "advanced",
    type: "number",
    label: "Limit — dist max file bytes",
    fallback: 10485760,
    env: "PROJECT_DIST_MAX_FILE_BYTES",
    min: 65536,
    max: 26214400,
  },
  {
    key: "limits.dist.max_total_bytes",
    category: "limits",
    tier: "advanced",
    type: "number",
    label: "Limit — dist max total bytes",
    fallback: 52428800,
    env: "PROJECT_DIST_MAX_TOTAL_BYTES",
    min: 1048576,
    max: 209715200,
  },
  // ai (optional — tunable live)
  {
    key: "ai.timeout.moderation_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — moderation timeout (ms)",
    fallback: 30000,
    env: "AI_TIMEOUT_MODERATION_MS",
    min: 30000,
    max: 60000,
  },
  {
    key: "ai.timeout.discuss_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — discuss timeout (ms)",
    fallback: 90000,
    env: "AI_TIMEOUT_DISCUSS_MS",
    min: 30000,
    max: 180000,
  },
  {
    key: "ai.models_default",
    category: "ai",
    tier: "advanced",
    type: "string",
    label: "AI — default model id",
    fallback: "default-combo",
    env: "AI_MODELS",
    optionsSource: "nine_router_models",
  },
  {
    key: "ai.model.moderation",
    category: "ai",
    tier: "advanced",
    type: "string",
    label: "AI — moderation model id",
    fallback: "",
    env: "AI_MODEL_MODERATION",
    optionsSource: "nine_router_models",
  },
  {
    key: "ai.model.discuss",
    category: "ai",
    tier: "advanced",
    type: "string",
    label: "AI — discuss model id",
    fallback: "",
    env: "AI_MODEL_DISCUSS",
    optionsSource: "nine_router_models",
  },
  {
    key: "ai.model.build",
    category: "ai",
    tier: "advanced",
    type: "string",
    label: "AI — build/edit model id",
    fallback: "",
    env: "AI_MODEL_BUILD",
    optionsSource: "nine_router_models",
  },
  {
    key: "ai.timeout.discuss_card_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — discuss card timeout (ms)",
    fallback: 45000,
    env: "AI_TIMEOUT_DISCUSS_CARD_MS",
    min: 3000,
    max: 120000,
  },
  {
    key: "ai.timeout.discuss_one_call_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — discuss one-call timeout (ms)",
    fallback: 120000,
    env: "AI_TIMEOUT_DISCUSS_ONE_CALL_MS",
    min: 30000,
    max: 240000,
  },
  {
    key: "ai.timeout.discuss_tool_settle_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — discuss tool settle timeout (ms)",
    fallback: 30000,
    env: "AI_TIMEOUT_DISCUSS_TOOL_SETTLE_MS",
    min: 30000,
    max: 60000,
  },
  {
    key: "ai.timeout.chat_compaction_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — chat compaction timeout (ms)",
    fallback: 60000,
    env: "AI_TIMEOUT_CHAT_COMPACTION_MS",
    min: 30000,
    max: 120000,
  },
  {
    key: "ai.timeout.build_spec_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — build spec timeout (ms)",
    fallback: 120000,
    env: "AI_TIMEOUT_BUILD_SPEC_MS",
    min: 30000,
    max: 240000,
  },
  {
    key: "ai.timeout.source_generation_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — source generation timeout (ms)",
    fallback: 600000,
    env: "AI_TIMEOUT_SOURCE_GENERATION_MS",
    min: 120000,
    max: 600000,
  },
  {
    key: "ai.timeout.edit_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — edit timeout (ms)",
    fallback: 600000,
    env: "AI_TIMEOUT_EDIT_MS",
    min: 60000,
    max: 600000,
  },
  {
    key: "ai.timeout.edit_repair_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — edit repair timeout (ms)",
    fallback: 300000,
    env: "AI_TIMEOUT_EDIT_REPAIR_MS",
    min: 60000,
    max: 600000,
  },
  {
    key: "ai.agent.generate_max_steps",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — generate agent max steps",
    fallback: 30,
    env: "AI_AGENT_GENERATE_MAX_STEPS",
    min: 15,
    max: 60,
  },
  {
    key: "ai.agent.repair_max_steps",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — repair agent max steps",
    fallback: 12,
    env: "AI_AGENT_REPAIR_MAX_STEPS",
    min: 4,
    max: 40,
  },
  {
    key: "ai.agent.subagent_max_steps",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — subagent max steps",
    fallback: 8,
    env: "AI_AGENT_SUBAGENT_MAX_STEPS",
    min: 2,
    max: 15,
  },
];

export function findConfigEntry(key: string): ConfigEntry | undefined {
  return APP_SETTINGS.find((e) => e.key === key);
}
