import { afterEach, describe, expect, it, vi } from "vitest";

const {
  prismaProjectDeploymentFindManyMock,
  proxyDeploymentRequestMock,
  readProjectDistArtifactMock,
} = vi.hoisted(() => ({
  prismaProjectDeploymentFindManyMock: vi.fn(),
  proxyDeploymentRequestMock: vi.fn(),
  readProjectDistArtifactMock: vi.fn(),
}));

vi.mock("@/lib/prisma", () => ({
  prisma: {
    projectDeployment: {
      findMany: prismaProjectDeploymentFindManyMock,
      update: vi.fn(),
    },
  },
}));
vi.mock("@/lib/projects/runtime-artifacts", async () => {
  const actual = await vi.importActual<
    typeof import("@/lib/projects/runtime-artifacts")
  >("@/lib/projects/runtime-artifacts");

  return {
    ...actual,
    readProjectDistArtifact: readProjectDistArtifactMock,
  };
});
vi.mock("@/lib/projects/runtime-proxy", async () => {
  const actual = await vi.importActual<
    typeof import("@/lib/projects/runtime-proxy")
  >("@/lib/projects/runtime-proxy");

  return {
    ...actual,
    proxyDeploymentRequest: proxyDeploymentRequestMock,
  };
});

import { getHandler } from "../../tests/support/route-handler";

import { Route } from "@/routes/p.$slug.$";

const GET = getHandler(Route, "GET");

describe("published generated route", () => {
  afterEach(() => {
    vi.clearAllMocks();
    readProjectDistArtifactMock.mockResolvedValue([]);
    vi.unstubAllEnvs();
  });

  it("never resolves or proxies generated bytes while public execution is disabled", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "false");

    const response = await GET(
      new Request("https://app.example.com/p/warung"),
      { slug: "warung" },
    );

    expect(response.status).toBe(503);
    expect(response.headers.get("Cache-Control")).toBe("no-store");
    expect(prismaProjectDeploymentFindManyMock).not.toHaveBeenCalled();
    expect(proxyDeploymentRequestMock).not.toHaveBeenCalled();
  });

  it("redirects legacy control-plane links without forwarding query secrets", async () => {
    vi.stubEnv("NODE_ENV", "production");
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");
    vi.stubEnv("NEXT_PUBLIC_APP_URL", "https://app.example.com");
    vi.stubEnv("GENERATED_PUBLIC_ORIGIN", "https://sites.example.net");

    const response = await GET(
      new Request(
        "https://app.example.com/p/warung/assets/app.js?assetToken=secret",
      ),
      {
        _splat: "assets/app.js",
        slug: "warung",
      },
    );

    expect(response.status).toBe(307);
    expect(response.headers.get("Location")).toBe(
      "https://sites.example.net/p/warung/assets/app.js",
    );
    expect(response.headers.get("Cache-Control")).toBe("no-store");
    expect(prismaProjectDeploymentFindManyMock).not.toHaveBeenCalled();
  });

  it("redirects base site requests to have a trailing slash", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");

    const response = await GET(
      new Request("https://sites.example.net/p/warung"),
      {
        slug: "warung",
      },
    );

    expect(response.status).toBe(301);
    expect(response.headers.get("Location")).toBe("/p/warung/");
    expect(prismaProjectDeploymentFindManyMock).not.toHaveBeenCalled();
    expect(proxyDeploymentRequestMock).not.toHaveBeenCalled();
  });

  it("passes publicAssetRewrite through to proxyDeploymentRequest", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");
    prismaProjectDeploymentFindManyMock.mockResolvedValueOnce([
      {
        build: {
          artifactRef: "project-artifact:s3:dist:build_1",
          createdAt: new Date(),
          id: "build_1",
          projectId: "project_1",
          snapshot: {
            id: "snapshot_1",
            projectId: "project_1",
            project: {
              id: "project_1",
              title: "Warung",
              user: { bannedAt: null },
            },
          },
          snapshotId: "snapshot_1",
          status: "succeeded",
          updatedAt: new Date(),
        },
        buildId: "build_1",
        createdAt: new Date(),
        id: "deployment_1",
        kind: "published",
        projectId: "project_1",
        snapshot: { id: "snapshot_1", projectId: "project_1" },
        snapshotId: "snapshot_1",
        status: "running",
        updatedAt: new Date(),
      },
    ]);
    proxyDeploymentRequestMock.mockResolvedValueOnce(
      new Response("<html></html>", {
        headers: { "Content-Type": "text/html; charset=utf-8" },
      }),
    );

    const response = await GET(
      new Request("https://sites.example.net/p/warung/"),
      { slug: "warung" },
    );

    expect(response.status).toBe(200);
    expect(proxyDeploymentRequestMock).toHaveBeenCalledWith(
      expect.objectContaining({
        deploymentId: "deployment_1",
        noindex: false,
        pathSegments: [],
        publicAssetRewrite: { slug: "warung" },
      }),
    );
  });

  it("uses the accepted snapshot business name for public metadata", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");
    prismaProjectDeploymentFindManyMock.mockResolvedValueOnce([
      {
        build: {
          artifactRef: "project-artifact:s3:dist:build_accepted_name",
          createdAt: new Date(),
          id: "build_accepted_name",
          projectId: "project_1",
          snapshot: {
            id: "snapshot_accepted_name",
            metadata: {
              summary: { businessName: "Beras GG" },
              manifest: { routes: [{ path: "/", title: "Beras GG" }] },
            },
            projectId: "project_1",
            project: {
              id: "project_1",
              title: "buatin web jualan beras",
              user: { bannedAt: null },
            },
          },
          snapshotId: "snapshot_accepted_name",
          status: "succeeded",
          updatedAt: new Date(),
        },
        buildId: "build_accepted_name",
        createdAt: new Date(),
        id: "deployment_accepted_name",
        kind: "published",
        projectId: "project_1",
        snapshot: {
          id: "snapshot_accepted_name",
          projectId: "project_1",
        },
        snapshotId: "snapshot_accepted_name",
        status: "running",
        updatedAt: new Date(),
      },
    ]);
    proxyDeploymentRequestMock.mockResolvedValueOnce(
      new Response("<html></html>", {
        headers: { "Content-Type": "text/html; charset=utf-8" },
      }),
    );

    await GET(new Request("https://sites.example.net/p/warung/"), {
      slug: "warung",
    });

    expect(proxyDeploymentRequestMock).toHaveBeenCalledWith(
      expect.objectContaining({ businessName: "Beras GG" }),
    );
  });

  it("returns 404 for a path outside the published route manifest", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");
    prismaProjectDeploymentFindManyMock.mockResolvedValueOnce([
      {
        build: {
          artifactRef: "project-artifact:s3:dist:build_unknown_path",
          createdAt: new Date(),
          id: "build_unknown_path",
          projectId: "project_1",
          snapshot: {
            id: "snapshot_unknown_path",
            metadata: {
              manifest: {
                routes: [{ path: "/", title: "Beranda" }],
              },
            },
            projectId: "project_1",
            project: {
              id: "project_1",
              title: "Warung",
              user: { bannedAt: null },
            },
          },
          snapshotId: "snapshot_unknown_path",
          status: "succeeded",
          updatedAt: new Date(),
        },
        buildId: "build_unknown_path",
        createdAt: new Date(),
        id: "deployment_unknown_path",
        kind: "published",
        projectId: "project_1",
        snapshot: {
          id: "snapshot_unknown_path",
          projectId: "project_1",
        },
        snapshotId: "snapshot_unknown_path",
        status: "running",
        updatedAt: new Date(),
      },
    ]);
    const response = await GET(
      new Request("https://sites.example.net/p/warung/missing"),
      { _splat: "missing", slug: "warung" },
    );

    expect(response.status).toBe(404);
    expect(response.headers.get("X-Robots-Tag")).toBe("noindex");
    expect(proxyDeploymentRequestMock).not.toHaveBeenCalled();
  });

  it("returns 404 for a missing published asset when the runtime is unavailable", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");
    prismaProjectDeploymentFindManyMock.mockResolvedValueOnce([
      {
        build: {
          artifactRef: "project-artifact:s3:dist:build_missing_asset",
          createdAt: new Date(),
          id: "build_missing_asset",
          projectId: "project_1",
          snapshot: {
            id: "snapshot_missing_asset",
            metadata: {
              manifest: { routes: [{ path: "/", title: "Beranda" }] },
            },
            projectId: "project_1",
            project: {
              id: "project_1",
              title: "Warung",
              user: { bannedAt: null },
            },
          },
          snapshotId: "snapshot_missing_asset",
          status: "succeeded",
          updatedAt: new Date(),
        },
        buildId: "build_missing_asset",
        createdAt: new Date(),
        id: "deployment_missing_asset",
        kind: "published",
        projectId: "project_1",
        snapshot: {
          id: "snapshot_missing_asset",
          projectId: "project_1",
        },
        snapshotId: "snapshot_missing_asset",
        status: "created",
        updatedAt: new Date(),
      },
    ]);
    proxyDeploymentRequestMock.mockResolvedValueOnce(null);
    readProjectDistArtifactMock.mockResolvedValueOnce([
      {
        content: "home",
        contentType: "text/html; charset=utf-8",
        path: "index.html",
      },
    ]);

    const response = await GET(
      new Request("https://sites.example.net/p/warung/assets/missing.js"),
      { _splat: "assets/missing.js", slug: "warung" },
    );

    expect(response.status).toBe(404);
    expect(response.headers.get("X-Robots-Tag")).toBe("noindex");
  });

  it("returns 410 for a published deployment whose owner is banned, without proxying", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");
    prismaProjectDeploymentFindManyMock.mockResolvedValueOnce([
      {
        build: {
          artifactRef: "project-artifact:s3:dist:build_banned",
          createdAt: new Date(),
          id: "build_banned",
          projectId: "project_1",
          snapshot: {
            id: "snapshot_banned",
            projectId: "project_1",
            project: {
              id: "project_1",
              title: "Warung",
              user: { bannedAt: new Date("2026-08-01") },
            },
          },
          snapshotId: "snapshot_banned",
          status: "succeeded",
          updatedAt: new Date(),
        },
        buildId: "build_banned",
        createdAt: new Date(),
        id: "deployment_banned",
        kind: "published",
        projectId: "project_1",
        snapshot: { id: "snapshot_banned", projectId: "project_1" },
        snapshotId: "snapshot_banned",
        status: "running",
        updatedAt: new Date(),
      },
    ]);

    const response = await GET(
      new Request("https://sites.example.net/p/warung/"),
      { slug: "warung" },
    );

    expect(response.status).toBe(410);
    expect(response.headers.get("X-Robots-Tag")).toBe("noindex");
    expect(response.headers.get("Cache-Control")).toBe("no-store");
    await expect(response.text()).resolves.toContain("Website tidak tersedia");
    expect(proxyDeploymentRequestMock).not.toHaveBeenCalled();
  });

  it("serves the published artifact when the runtime is unavailable", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");
    prismaProjectDeploymentFindManyMock.mockResolvedValueOnce([
      {
        build: {
          artifactRef: "project-artifact:s3:dist:build_2",
          createdAt: new Date(),
          id: "build_2",
          projectId: "project_1",
          snapshot: {
            id: "snapshot_2",
            projectId: "project_1",
            project: {
              id: "project_1",
              title: "Warung",
              user: { bannedAt: null },
            },
          },
          snapshotId: "snapshot_2",
          status: "succeeded",
          updatedAt: new Date(),
        },
        buildId: "build_2",
        createdAt: new Date(),
        id: "deployment_2",
        kind: "published",
        projectId: "project_1",
        snapshot: { id: "snapshot_2", projectId: "project_1" },
        snapshotId: "snapshot_2",
        status: "created",
        updatedAt: new Date(),
      },
    ]);
    proxyDeploymentRequestMock.mockResolvedValueOnce(null);
    readProjectDistArtifactMock.mockResolvedValueOnce([
      {
        content:
          '<html><head></head><body><script src="./assets/app.js"></script></body></html>',
        contentType: "text/html; charset=utf-8",
        path: "index.html",
      },
    ]);

    const response = await GET(
      new Request("https://sites.example.net/p/warung/"),
      { slug: "warung" },
    );

    expect(response.status).toBe(200);
    await expect(response.text()).resolves.toContain("/p/warung/assets/app.js");
    expect(readProjectDistArtifactMock).toHaveBeenCalledWith(
      "project-artifact:s3:dist:build_2",
    );
  });

  it("does not proxy or read a published artifact reference owned by another build", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");
    prismaProjectDeploymentFindManyMock.mockResolvedValueOnce([
      {
        build: {
          artifactRef: "project-artifact:s3:dist:other_build",
          createdAt: new Date(),
          id: "build_1",
          projectId: "project_1",
          snapshot: {
            metadata: { manifest: { routes: [{ path: "/" }] } },
            projectId: "project_1",
            project: {
              id: "project_1",
              title: "Warung",
              user: { bannedAt: null },
            },
          },
          snapshotId: "snapshot_1",
          status: "succeeded",
          updatedAt: new Date(),
        },
        buildId: "build_1",
        createdAt: new Date(),
        id: "deployment_1",
        kind: "published",
        projectId: "project_1",
        snapshot: { projectId: "project_1" },
        snapshotId: "snapshot_1",
        status: "running",
        updatedAt: new Date(),
      },
    ]);

    const response = await GET(
      new Request("https://sites.example.net/p/warung/"),
      { slug: "warung" },
    );

    expect(response.status).toBe(404);
    expect(proxyDeploymentRequestMock).not.toHaveBeenCalled();
    expect(readProjectDistArtifactMock).not.toHaveBeenCalled();
  });

  it("still proxies for an active (non-banned) owner", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");
    prismaProjectDeploymentFindManyMock.mockResolvedValueOnce([
      {
        build: {
          artifactRef: "project-artifact:s3:dist:build_2",
          createdAt: new Date(),
          id: "build_2",
          projectId: "project_1",
          snapshotId: "snapshot_2",
          snapshot: {
            id: "snapshot_2",
            projectId: "project_1",
            project: {
              id: "project_1",
              title: "Warung",
              user: { bannedAt: null },
            },
          },
          status: "succeeded",
          updatedAt: new Date(),
        },
        buildId: "build_2",
        createdAt: new Date(),
        id: "deployment_2",
        kind: "published",
        projectId: "project_1",
        snapshot: { id: "snapshot_2", projectId: "project_1" },
        snapshotId: "snapshot_2",
        status: "running",
        updatedAt: new Date(),
      },
    ]);
    proxyDeploymentRequestMock.mockResolvedValueOnce(
      new Response("<html></html>", {
        headers: { "Content-Type": "text/html; charset=utf-8" },
      }),
    );

    const response = await GET(
      new Request("https://sites.example.net/p/warung/"),
      { slug: "warung" },
    );

    expect(response.status).toBe(200);
    expect(proxyDeploymentRequestMock).toHaveBeenCalled();
  });
});
