import { afterEach, describe, expect, it, vi } from "vitest";

const { prismaProjectDeploymentFindManyMock, proxyDeploymentRequestMock } =
  vi.hoisted(() => ({
    prismaProjectDeploymentFindManyMock: vi.fn(),
    proxyDeploymentRequestMock: vi.fn(),
  }));

vi.mock("@/lib/prisma", () => ({
  prisma: {
    projectDeployment: {
      findMany: prismaProjectDeploymentFindManyMock,
      update: vi.fn(),
    },
  },
}));
vi.mock("@/lib/projects/runtime-proxy", () => ({
  proxyDeploymentRequest: proxyDeploymentRequestMock,
}));

import { getHandler } from "../../tests/support/route-handler";

import { Route } from "@/routes/p.$slug.$";

const GET = getHandler(Route, "GET");

describe("published generated route", () => {
  afterEach(() => {
    vi.clearAllMocks();
    vi.unstubAllEnvs();
  });

  it("never resolves or proxies generated bytes while public execution is disabled", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "false");

    const response = await GET(
      new Request("https://app.example.com/p/warung"),
      { slug: "warung" },
    );

    expect(response.status).toBe(503);
    expect(response.headers.get("Cache-Control")).toBe("no-store");
    expect(prismaProjectDeploymentFindManyMock).not.toHaveBeenCalled();
    expect(proxyDeploymentRequestMock).not.toHaveBeenCalled();
  });

  it("redirects legacy control-plane links without forwarding query secrets", async () => {
    vi.stubEnv("NODE_ENV", "production");
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");
    vi.stubEnv("NEXT_PUBLIC_APP_URL", "https://app.example.com");
    vi.stubEnv("GENERATED_PUBLIC_ORIGIN", "https://sites.example.net");

    const response = await GET(
      new Request(
        "https://app.example.com/p/warung/assets/app.js?assetToken=secret",
      ),
      {
        _splat: "assets/app.js",
        slug: "warung",
      },
    );

    expect(response.status).toBe(307);
    expect(response.headers.get("Location")).toBe(
      "https://sites.example.net/p/warung/assets/app.js",
    );
    expect(response.headers.get("Cache-Control")).toBe("no-store");
    expect(prismaProjectDeploymentFindManyMock).not.toHaveBeenCalled();
  });

  it("redirects base site requests to have a trailing slash", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");

    const response = await GET(
      new Request("https://sites.example.net/p/warung"),
      {
        slug: "warung",
      },
    );

    expect(response.status).toBe(301);
    expect(response.headers.get("Location")).toBe("/p/warung/");
    expect(prismaProjectDeploymentFindManyMock).not.toHaveBeenCalled();
    expect(proxyDeploymentRequestMock).not.toHaveBeenCalled();
  });

  it("passes publicAssetRewrite through to proxyDeploymentRequest", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");
    prismaProjectDeploymentFindManyMock.mockResolvedValueOnce([
      {
        build: {
          artifactRef: "project-artifact:local:dist:abc",
          createdAt: new Date(),
          id: "build_1",
          snapshotId: "snapshot_1",
          status: "succeeded",
          updatedAt: new Date(),
        },
        buildId: "build_1",
        createdAt: new Date(),
        id: "deployment_1",
        kind: "published",
        snapshotId: "snapshot_1",
        status: "running",
        updatedAt: new Date(),
      },
    ]);
    proxyDeploymentRequestMock.mockResolvedValueOnce(
      new Response("<html></html>", {
        headers: { "Content-Type": "text/html; charset=utf-8" },
      }),
    );

    const response = await GET(
      new Request("https://sites.example.net/p/warung/"),
      { slug: "warung" },
    );

    expect(response.status).toBe(200);
    expect(proxyDeploymentRequestMock).toHaveBeenCalledWith(
      expect.objectContaining({
        deploymentId: "deployment_1",
        noindex: false,
        pathSegments: [],
        publicAssetRewrite: { slug: "warung" },
      }),
    );
  });

  it("returns 410 for a published deployment whose owner is banned, without proxying", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");
    prismaProjectDeploymentFindManyMock.mockResolvedValueOnce([
      {
        build: {
          artifactRef: "project-artifact:local:dist:abc",
          createdAt: new Date(),
          id: "build_banned",
          snapshotId: "snapshot_banned",
          snapshot: {
            project: {
              title: "Warung",
              user: { bannedAt: new Date("2026-08-01") },
            },
          },
          status: "succeeded",
          updatedAt: new Date(),
        },
        buildId: "build_banned",
        createdAt: new Date(),
        id: "deployment_banned",
        kind: "published",
        snapshotId: "snapshot_banned",
        status: "running",
        updatedAt: new Date(),
      },
    ]);

    const response = await GET(
      new Request("https://sites.example.net/p/warung/"),
      { slug: "warung" },
    );

    expect(response.status).toBe(410);
    expect(response.headers.get("X-Robots-Tag")).toBe("noindex");
    expect(response.headers.get("Cache-Control")).toBe("no-store");
    expect(proxyDeploymentRequestMock).not.toHaveBeenCalled();
  });

  it("still proxies for an active (non-banned) owner", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");
    prismaProjectDeploymentFindManyMock.mockResolvedValueOnce([
      {
        build: {
          artifactRef: "project-artifact:local:dist:abc",
          createdAt: new Date(),
          id: "build_2",
          snapshotId: "snapshot_2",
          snapshot: {
            project: { title: "Warung", user: { bannedAt: null } },
          },
          status: "succeeded",
          updatedAt: new Date(),
        },
        buildId: "build_2",
        createdAt: new Date(),
        id: "deployment_2",
        kind: "published",
        snapshotId: "snapshot_2",
        status: "running",
        updatedAt: new Date(),
      },
    ]);
    proxyDeploymentRequestMock.mockResolvedValueOnce(
      new Response("<html></html>", {
        headers: { "Content-Type": "text/html; charset=utf-8" },
      }),
    );

    const response = await GET(
      new Request("https://sites.example.net/p/warung/"),
      { slug: "warung" },
    );

    expect(response.status).toBe(200);
    expect(proxyDeploymentRequestMock).toHaveBeenCalled();
  });
});
