import { prisma } from '@/lib/prisma';
import { NextResponse } from 'next/server';
// Import the base schema for omit
import {
  generateLandingPageContent,
  generateColorTheme, // Import the color theme generator
  AiGeneratedContent, // Import the new interface
  type ColorThemeJson
} from '@/lib/ai';
import { fileToBuffer, uploadImageToCloudinary } from '@/lib/cloudinary';
import { checkRateLimit } from '@/lib/rate-limit'; // Import rate limit checker
import { generateRandomString, slugify } from '@/lib/utils';
// Import the base schema to apply refinement after omit
// import type { ColorThemeJson } from '@/lib/ai'; // REMOVE THIS LINE if present
import { auth } from '@/lib/auth'; // Import auth untuk cek sesi
import { baseLandingPageSchemaForOmit } from '@/lib/zod-schemas';

// Define types for testimonials and social links
type Testimonial = {
  name: string;
  comment: string;
}

type SocialLink = {
  platform: string;
  url: string;
}

// Definisikan tema warna default (REMOVED, will use default from AI if needed)
// const defaultColorTheme: ColorThemeJson = { ... };

// POST /api/landing - Create a new landing page
export async function POST(request: Request) {
  try {
    // Apply rate limiting first
    const rateLimitResponse = await checkRateLimit(request, 'ai');
    if (rateLimitResponse) return rateLimitResponse;

    // Cek sesi user (tidak wajib login)
    const session = await auth();
    const userId = session?.user?.id; // Bisa null jika tidak login

    const formData = await request.formData();

    // REMOVE colorThemeJson extraction from formData, it will be generated by AI
    // const colorThemeJsonString = formData.get('colorThemeJson') as string | null;
    const rawData = {
      namaUsaha: formData.get('namaUsaha'),
      kategori: formData.get('kategori'),
      kategoriLainnya: formData.get('kategoriLainnya'),
      deskripsi_user: formData.get('deskripsi_user'),
      whatsapp: formData.get('whatsapp'),
      // colorThemeJson: colorThemeJsonString, // REMOVED from rawData
      // Images handled later
    };

    // Validate text fields ONLY (omit colorThemeJson)
    const validationSchema = baseLandingPageSchemaForOmit
      .omit({ images: true, colorThemeJson: true }) // Omit color theme from Zod validation
      .refine((data) => {
        if (data.kategori === 'Lainnya') {
          return !!data.kategoriLainnya && data.kategoriLainnya.trim().length > 0;
        }
        return true;
      }, {
        message: 'Nama kategori harus diisi jika memilih \'Lainnya\'',
        path: ['kategoriLainnya'],
      });

    // Gunakan skema baru untuk validasi
    const validationResult = validationSchema.safeParse(rawData);

    if (!validationResult.success) {
      console.error("Validation Errors:", validationResult.error.flatten());
      return NextResponse.json(
        { message: 'Data tidak valid', errors: validationResult.error.flatten().fieldErrors },
        { status: 400 }
      );
    }

    // Ambil data yang sudah divalidasi (tanpa colorThemeJson)
    const { namaUsaha, kategori, deskripsi_user, whatsapp } = validationResult.data;
    const finalKategori = kategori === 'Lainnya' ? formData.get('kategoriLainnya') as string : kategori;

    // Handle Image Uploads to Cloudinary
    const imageFiles = formData.getAll('images') as File[];
    const uploadedImageData: { url: string; publicId: string }[] = [];

    if (imageFiles && imageFiles.length > 0 && imageFiles[0].size > 0) {
      // Validate image count/type/size again on the server (optional but recommended)
      if (imageFiles.length > 3) {
        return NextResponse.json({ message: 'Maksimal 3 gambar' }, { status: 400 });
      }
      // Add more server-side validation if needed (size, type)

      for (const file of imageFiles) {
        try {
          const buffer = await fileToBuffer(file);
          const uniqueFileName = `${slugify(namaUsaha)}-${generateRandomString(4)}-${Date.now()}`;
          // Get both url and publicId
          const { secure_url, public_id } = await uploadImageToCloudinary(buffer, uniqueFileName);
          uploadedImageData.push({ url: secure_url, publicId: public_id });
        } catch (uploadError) {
          console.error("Image upload failed:", uploadError);
          return NextResponse.json({ message: 'Gagal mengupload salah satu gambar.' }, { status: 500 });
        }
      }
    }

    // Generate unique slug
    let pageSlug = slugify(namaUsaha);
    let existingPage = await prisma.landingPage.findUnique({ where: { slug: pageSlug } });
    let attempts = 0;
    while (existingPage && attempts < 5) {
      pageSlug = `${slugify(namaUsaha)}-${generateRandomString(6)}`;
      existingPage = await prisma.landingPage.findUnique({ where: { slug: pageSlug } });
      attempts++;
    }
    if (existingPage) {
      throw new Error("Gagal membuat slug unik setelah beberapa percobaan.");
    }

    // --- Generate AI Content & Color Theme --- 
    console.time("AI Content Generation");
    const hasWhatsApp = !!whatsapp && whatsapp.length > 5;
    let aiContent: AiGeneratedContent;
    try {
      aiContent = await generateLandingPageContent(
        namaUsaha,
        finalKategori,
        deskripsi_user || undefined,
        hasWhatsApp
      );
      // Apply WhatsApp number if generated CTA needs it
      if (aiContent.whatsappCTA && hasWhatsApp) {
        aiContent.whatsappNumber = whatsapp;
      } else if (aiContent.whatsappCTA && !hasWhatsApp) {
        console.warn("AI suggested WhatsApp CTA but no number provided by user. Overriding.");
        aiContent.whatsappCTA = false;
        delete aiContent.whatsappNumber;
      } else if (!aiContent.whatsappCTA) {
        delete aiContent.whatsappNumber;
      }
    } catch (aiError) {
      console.error("AI Content generation failed:", aiError);
      // Return specific error or potentially fallback to basic content?
      // For now, rethrow as a user-facing error
      throw new Error("Gagal menghasilkan konten AI utama. Coba lagi.");
    }
    console.timeEnd("AI Content Generation");

    console.time("AI Color Theme Generation");
    let colorTheme: ColorThemeJson;
    try {
      colorTheme = await generateColorTheme(namaUsaha, finalKategori);
    } catch (colorError) {
      console.error("AI Color Theme generation failed:", colorError);
      // Consider using a hardcoded default theme as fallback?
      // For now, rethrow as a user-facing error
      throw new Error("Gagal menghasilkan tema warna AI. Coba lagi.");
    }
    console.timeEnd("AI Color Theme Generation");
    // --- End AI Generation --- 

    // === Get Optional Fields ===
    const testimonialsString = formData.get('testimonials') as string | null;
    const address = formData.get('address') as string | null;
    const socialLinksString = formData.get('socialLinks') as string | null;

    // Parse JSON strings into arrays
    let testimonials: Testimonial[] = [];
    try {
      testimonials = testimonialsString ? JSON.parse(testimonialsString) : [];
    } catch (e) {
      console.error("Failed to parse testimonials JSON:", e);
      // Handle error, maybe return bad request?
    }

    let socialLinks: SocialLink[] = [];
    try {
      socialLinks = socialLinksString ? JSON.parse(socialLinksString) : [];
    } catch (e) {
      console.error("Failed to parse socialLinks JSON:", e);
      // Handle error
    }

    // Add logging to check the userId value before saving
    console.log(`Attempting to create LandingPage with userId: ${userId ?? 'null'}`);

    // Save to Database
    console.time("Database Write"); // Start timing DB write
    /* eslint-disable @typescript-eslint/no-explicit-any */
    const newLandingPage = await prisma.landingPage.create({
      data: {
        slug: pageSlug,
        namaUsaha: namaUsaha,
        kategori: finalKategori,
        whatsapp: whatsapp || null,
        aiContent: aiContent as any, // Store the whole new structure
        colorTheme: colorTheme as any, // Store the generated color theme
        images: uploadedImageData.map(img => img.url),
        imagePublicIds: uploadedImageData.map(img => img.publicId),
        userId: userId,
        isClaimed: !!userId,
        tweaksLeft: 5,
        address: address || null,
        testimonials: testimonials as any,
        socialLinks: socialLinks as any,
      },
    });
    console.timeEnd("Database Write"); // End timing DB write

    console.log("New Landing Page Created:", newLandingPage.id, "Slug:", pageSlug, "UserID:", userId);

    // Return slug ONLY (tanpa edit token)
    return NextResponse.json(
      { slug: pageSlug, message: 'Landing page berhasil dibuat!' },
      { status: 201 }
    );

  } catch (error) {
    console.error("Error creating landing page:", error);
    let message = 'Terjadi kesalahan saat membuat halaman.';
    if (error instanceof Error) {
      // Don't expose sensitive internal messages directly
      if (error.message.includes("Cloudinary")) {
        message = "Gagal mengupload gambar. Coba lagi.";
      } else if (error.message.includes("konten AI utama")) {
        message = error.message; // Use the specific error from content generation
      } else if (error.message.includes("tema warna AI")) {
        message = error.message; // Use the specific error from color generation
      } else if (error.message.includes("slug unik")) {
        message = "Gagal membuat alamat unik untuk halaman Anda. Coba nama usaha yang sedikit berbeda.";
      } else if (error.message.includes("AI")) { // Catch-all for other AI errors
        message = "Terjadi kesalahan pada proses AI. Coba lagi nanti.";
      }
      // Log full error server-side for debugging
    }
    return NextResponse.json({ message }, { status: 500 });
  }
}

// Note: We might need a PUT/PATCH endpoint later for the /edit/[slug] page
// PUT /api/landing/[slug]?token=...
// OR handle edits via Server Actions 