import { afterEach, describe, expect, it, vi } from "vitest";

const { prismaProjectDeploymentFindManyMock, proxyDeploymentRequestMock } =
  vi.hoisted(() => ({
    prismaProjectDeploymentFindManyMock: vi.fn(),
    proxyDeploymentRequestMock: vi.fn(),
  }));

vi.mock("@/lib/prisma", () => ({
  prisma: {
    projectDeployment: {
      findMany: prismaProjectDeploymentFindManyMock,
      update: vi.fn(),
    },
  },
}));
vi.mock("@/lib/projects/runtime-proxy", () => ({
  proxyDeploymentRequest: proxyDeploymentRequestMock,
}));

import { getHandler } from "./_handler";

import { Route } from "@/routes/p.$slug.$";

const GET = getHandler(Route, "GET");

describe("published generated route", () => {
  afterEach(() => {
    vi.clearAllMocks();
    vi.unstubAllEnvs();
  });

  it("never resolves or proxies generated bytes while public execution is disabled", async () => {
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "false");

    const response = await GET(
      new Request("https://app.example.com/p/warung"),
      { slug: "warung" },
    );

    expect(response.status).toBe(503);
    expect(response.headers.get("Cache-Control")).toBe("no-store");
    expect(prismaProjectDeploymentFindManyMock).not.toHaveBeenCalled();
    expect(proxyDeploymentRequestMock).not.toHaveBeenCalled();
  });

  it("redirects legacy control-plane links without forwarding query secrets", async () => {
    vi.stubEnv("NODE_ENV", "production");
    vi.stubEnv("GENERATED_PUBLIC_EXECUTION_ENABLED", "true");
    vi.stubEnv("NEXT_PUBLIC_APP_URL", "https://app.example.com");
    vi.stubEnv("GENERATED_PUBLIC_ORIGIN", "https://sites.example.net");

    const response = await GET(
      new Request(
        "https://app.example.com/p/warung/assets/app.js?assetToken=secret",
      ),
      {
        _splat: "assets/app.js",
        slug: "warung",
      },
    );

    expect(response.status).toBe(307);
    expect(response.headers.get("Location")).toBe(
      "https://sites.example.net/p/warung/assets/app.js",
    );
    expect(response.headers.get("Cache-Control")).toBe("no-store");
    expect(prismaProjectDeploymentFindManyMock).not.toHaveBeenCalled();
  });
});
