export type SettingType = "boolean" | "number" | "string";
export type SettingTier = "basic" | "advanced";
export type SettingCategory =
  | "feature_flag"
  | "economics"
  | "booster"
  | "ai"
  | "rate_limit"
  | "runtime"
  | "limits";

// Render order on /admin/settings. Basic categories render expanded; advanced
export const CATEGORY_ORDER = [
  "feature_flag",
  "economics",
  "booster",
  "ai",
  "rate_limit",
  "runtime",
  "limits",
] as const satisfies readonly SettingCategory[];

export const CATEGORY_TIER: Record<SettingCategory, SettingTier> = {
  feature_flag: "basic",
  economics: "basic",
  booster: "basic",
  ai: "advanced",
  rate_limit: "advanced",
  runtime: "advanced",
  limits: "advanced",
};

export type ConfigEntry = {
  key: string;
  category: SettingCategory;
  type: SettingType;
  label: string;
  fallback: boolean | number | string;
  tier: SettingTier;
  // Canonical env var name. Omitted when the setting has no env equivalent.
  env?: string;
  // Inclusive bounds, numbers only. Enforced on write by the admin PUT handler
  min?: number;
  max?: number;
  // True when the value is read once at process start, so a change needs a
  requiresRestart?: boolean;
  // When set, /admin/settings renders a select populated from this source
  optionsSource?: "nine_router_models";
  // When set, /admin/settings renders a fixed-option select (enum). Mutually
  enumOptions?: readonly string[];
  display?: "percentage";
};

// Source of truth for DB-overridable, non-secret config. Adding a setting
export const APP_SETTINGS: ConfigEntry[] = [
  // feature_flag
  {
    key: "feature.maintenance_mode",
    category: "feature_flag",
    tier: "basic",
    type: "boolean",
    label: "Mode Pemeliharaan (Maintenance Mode)",
    fallback: false,
    env: "MAINTENANCE_MODE",
  },
  {
    key: "feature.maintenance_message",
    category: "feature_flag",
    tier: "basic",
    type: "string",
    label: "Pesan Pemeliharaan Sistem",
    fallback:
      "Sistem sedang dalam pemeliharaan berkala untuk peningkatan server. Semua data website Anda tetap aman.",
  },
  {
    key: "feature.waitlist_enabled",
    category: "feature_flag",
    tier: "basic",
    type: "boolean",
    label: "Waitlist onboarding gate",
    fallback: true,
    env: "WAITLIST_ENABLED",
  },
  {
    key: "feature.streamer_mode",
    category: "feature_flag",
    tier: "basic",
    type: "boolean",
    label: "Streamer mode (mask PII in admin)",
    fallback: true,
  },
  {
    key: "feature.default_theme",
    category: "feature_flag",
    tier: "basic",
    type: "string",
    label: "Tema Bawaan Situs (Default Theme)",
    fallback: "system",
    enumOptions: ["dark", "light", "system"],
  },

  {
    key: "feature.composer_uploads_enabled",
    category: "feature_flag",
    tier: "basic",
    type: "boolean",
    label: "Composer image uploads",
    fallback: false,
  },
  {
    key: "feature.visual_edit_enabled",
    category: "feature_flag",
    tier: "basic",
    type: "boolean",
    label: "Workspace Tunjuk & Ubah (visual edit) mode",
    fallback: false,
  },
  // economics
  {
    key: "economics.project_limit",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Batas proyek per pengguna",
    fallback: 5,
    env: "PROJECT_LIMIT",
    min: 1,
    max: 100,
  },
  {
    key: "economics.signup_energy_grant",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi awal pengguna",
    fallback: 500000,
    min: 10000,
    max: 5000000,
  },
  {
    key: "economics.min_energy_discuss",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi minimum — diskusi",
    fallback: 5000,
    min: 0,
    max: 100000,
  },
  {
    key: "economics.min_energy_build",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi minimum — build",
    fallback: 40000,
    min: 0,
    max: 500000,
  },
  {
    key: "economics.min_energy_edit",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi minimum — edit",
    fallback: 10000,
    min: 0,
    max: 200000,
  },
  {
    key: "economics.min_energy_moderation",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Energi minimum — moderasi",
    fallback: 500,
    min: 0,
    max: 50000,
  },
  {
    key: "economics.micro_usd_per_energy",
    category: "economics",
    tier: "basic",
    type: "number",
    label: "Micro-USD per energi",
    fallback: 1000000,
    min: 1000,
    max: 100000000,
  },
  // booster (fallbacks mirror BOOSTER_PACKS in mayar.ts)
  {
    key: "booster.popular_pack_id",
    category: "booster",
    tier: "basic",
    type: "string",
    label: "Paket yang ditandai Terlaris",
    fallback: "starter",
    enumOptions: ["pocket", "starter", "popular", "max", "none"],
  },
  {
    key: "booster.pocket.amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Pocket — harga jual (Rp)",
    fallback: 4900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.pocket.compare_at_amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Pocket — harga coret (Rp)",
    fallback: 7900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.pocket.energy",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Pocket — energy",
    fallback: 50000,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.pocket.name",
    category: "booster",
    tier: "basic",
    type: "string",
    label: "Pocket — nama paket",
    fallback: "Eceran Hemat",
  },
  {
    key: "booster.pocket.desc",
    category: "booster",
    tier: "basic",
    type: "string",
    label: "Pocket — deskripsi",
    fallback: "Pas buat uji coba fitur",
  },
  {
    key: "booster.starter.amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Starter — harga jual (Rp)",
    fallback: 14900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.starter.compare_at_amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Starter — harga coret (Rp)",
    fallback: 24900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.starter.energy",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Starter — energy",
    fallback: 200000,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.starter.name",
    category: "booster",
    tier: "basic",
    type: "string",
    label: "Starter — nama paket",
    fallback: "Usaha Rintisan",
  },
  {
    key: "booster.starter.desc",
    category: "booster",
    tier: "basic",
    type: "string",
    label: "Starter — deskripsi",
    fallback: "Ideal untuk toko online pemula",
  },
  {
    key: "booster.popular.amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Popular — harga jual (Rp)",
    fallback: 39900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.popular.compare_at_amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Popular — harga coret (Rp)",
    fallback: 69900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.popular.energy",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Popular — energy",
    fallback: 600000,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.popular.name",
    category: "booster",
    tier: "basic",
    type: "string",
    label: "Popular — nama paket",
    fallback: "Laris Manis",
  },
  {
    key: "booster.popular.desc",
    category: "booster",
    tier: "basic",
    type: "string",
    label: "Popular — deskripsi",
    fallback: "Pendamping tumbuh cepat",
  },
  {
    key: "booster.max.amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Max — harga jual (Rp)",
    fallback: 99900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.max.compare_at_amount",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Max — harga coret (Rp)",
    fallback: 179900,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.max.energy",
    category: "booster",
    tier: "basic",
    type: "number",
    label: "Max — energy",
    fallback: 1500000,
    min: 0,
    max: 100_000_000,
  },
  {
    key: "booster.max.name",
    category: "booster",
    tier: "basic",
    type: "string",
    label: "Max — nama paket",
    fallback: "Juragan Besar",
  },
  {
    key: "booster.max.desc",
    category: "booster",
    tier: "basic",
    type: "string",
    label: "Max — deskripsi",
    fallback: "Energi tambahan melimpah",
  },
  // rate_limit (fallbacks mirror rate-limit.ts defaults)
  {
    key: "ratelimit.global_ip.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Global IP — requests",
    fallback: 300,
    env: "RATE_LIMIT_GLOBAL_IP_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.global_ip.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Global IP — window (s)",
    fallback: 60,
    env: "RATE_LIMIT_GLOBAL_IP_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  {
    key: "ratelimit.ai_user.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "AI user — requests",
    fallback: 60,
    env: "RATE_LIMIT_AI_USER_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.ai_user.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "AI user — window (s)",
    fallback: 600,
    env: "RATE_LIMIT_AI_USER_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  {
    key: "ratelimit.ai_ip.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "AI IP — requests",
    fallback: 20,
    env: "RATE_LIMIT_AI_IP_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.ai_ip.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "AI IP — window (s)",
    fallback: 600,
    env: "RATE_LIMIT_AI_IP_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  {
    key: "ratelimit.build_user.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Build user — requests",
    fallback: 10,
    env: "RATE_LIMIT_BUILD_USER_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.build_user.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Build user — window (s)",
    fallback: 3600,
    env: "RATE_LIMIT_BUILD_USER_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  {
    key: "ratelimit.build_ip.requests",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Build IP — requests",
    fallback: 5,
    env: "RATE_LIMIT_BUILD_IP_REQUESTS",
    min: 1,
    max: 100000,
  },
  {
    key: "ratelimit.build_ip.window_seconds",
    category: "rate_limit",
    tier: "advanced",
    type: "number",
    label: "Build IP — window (s)",
    fallback: 3600,
    env: "RATE_LIMIT_BUILD_IP_WINDOW_SECONDS",
    min: 1,
    max: 86400,
  },
  // runtime
  {
    key: "runtime.build_concurrency",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — build concurrency",
    fallback: 3,
    env: "PROJECT_BUILD_CONCURRENCY",
    min: 1,
    max: 16,
  },
  {
    key: "runtime.generated_build_timeout_ms",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — generated build timeout (ms)",
    fallback: 90_000,
    env: "PROJECT_GENERATED_BUILD_TIMEOUT_MS",
    min: 30_000,
    max: 180_000,
  },
  {
    key: "runtime.max_containers",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — max containers",
    fallback: 8,
    env: "PROJECT_RUNTIME_MAX_CONTAINERS",
    min: 1,
    max: 64,
  },
  {
    key: "runtime.health_timeout_ms",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — health timeout (ms)",
    fallback: 2000,
    env: "PROJECT_RUNTIME_HEALTH_TIMEOUT_MS",
    min: 500,
    max: 5000,
  },
  {
    key: "runtime.proxy_timeout_ms",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — proxy timeout (ms)",
    fallback: 15000,
    env: "PROJECT_RUNTIME_PROXY_TIMEOUT_MS",
    min: 1000,
    max: 30000,
  },
  {
    key: "runtime.preview_token_ttl_seconds",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — preview token TTL (s)",
    fallback: 300,
    env: "PREVIEW_ASSET_TOKEN_TTL_SECONDS",
    min: 60,
    max: 900,
  },
  {
    key: "runtime.thumbnail_concurrency",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — thumbnail concurrency",
    fallback: 1,
    env: "PROJECT_THUMBNAIL_CONCURRENCY",
    min: 1,
    max: 8,
  },
  {
    key: "runtime.thumbnail_timeout_ms",
    category: "runtime",
    tier: "advanced",
    type: "number",
    label: "Runtime — thumbnail timeout (ms)",
    fallback: 15000,
    env: "PROJECT_THUMBNAIL_TIMEOUT_MS",
    min: 1000,
    max: 120000,
  },
  // limits
  {
    key: "limits.source.max_files",
    category: "limits",
    tier: "advanced",
    type: "number",
    label: "Limit — source max files",
    fallback: 100,
    env: "PROJECT_SOURCE_MAX_FILES",
    min: 10,
    max: 500,
  },
  {
    key: "limits.source.max_file_bytes",
    category: "limits",
    tier: "advanced",
    type: "number",
    label: "Limit — source max file bytes",
    fallback: 262144,
    env: "PROJECT_SOURCE_MAX_FILE_BYTES",
    min: 16384,
    max: 1048576,
  },
  {
    key: "limits.source.max_total_bytes",
    category: "limits",
    tier: "advanced",
    type: "number",
    label: "Limit — source max total bytes",
    fallback: 5242880,
    env: "PROJECT_SOURCE_MAX_TOTAL_BYTES",
    min: 262144,
    max: 20971520,
  },
  {
    key: "limits.dist.max_files",
    category: "limits",
    tier: "advanced",
    type: "number",
    label: "Limit — dist max files",
    fallback: 500,
    env: "PROJECT_DIST_MAX_FILES",
    min: 10,
    max: 2000,
  },
  {
    key: "limits.dist.max_file_bytes",
    category: "limits",
    tier: "advanced",
    type: "number",
    label: "Limit — dist max file bytes",
    fallback: 10485760,
    env: "PROJECT_DIST_MAX_FILE_BYTES",
    min: 65536,
    max: 26214400,
  },
  {
    key: "limits.dist.max_total_bytes",
    category: "limits",
    tier: "advanced",
    type: "number",
    label: "Limit — dist max total bytes",
    fallback: 52428800,
    env: "PROJECT_DIST_MAX_TOTAL_BYTES",
    min: 1048576,
    max: 209715200,
  },
  // ai (optional — tunable live)
  {
    key: "ai.timeout.agentic_generate_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — generation step timeout (ms)",
    fallback: 180000,
    env: "AI_TIMEOUT_AGENTIC_GENERATE_MS",
    min: 30000,
    max: 300000,
  },
  {
    key: "discuss.chat.auto_retry_attempts",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — discuss auto-retry attempts",
    fallback: 2,
    min: 0,
    max: 5,
    env: "DISCUSS_CHAT_AUTO_RETRY_ATTEMPTS",
  },
  {
    key: "discuss.chat.auto_retry_delay_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — discuss auto-retry delay (ms)",
    fallback: 4000,
    min: 1000,
    max: 15000,
    env: "DISCUSS_CHAT_AUTO_RETRY_DELAY_MS",
  },
  {
    key: "ai.timeout.moderation_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — moderation timeout (ms)",
    fallback: 30000,
    env: "AI_TIMEOUT_MODERATION_MS",
    min: 30000,
    max: 60000,
  },
  {
    key: "ai.timeout.discuss_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — discuss timeout (ms)",
    fallback: 90000,
    env: "AI_TIMEOUT_DISCUSS_MS",
    min: 30000,
    max: 180000,
  },
  {
    key: "ai.models_default",
    category: "ai",
    tier: "advanced",
    type: "string",
    label: "AI — default model id",
    fallback: "default-combo",
    env: "AI_MODELS",
    optionsSource: "nine_router_models",
  },
  {
    key: "ai.model.moderation",
    category: "ai",
    tier: "advanced",
    type: "string",
    label: "AI — moderation model id",
    fallback: "",
    env: "AI_MODEL_MODERATION",
    optionsSource: "nine_router_models",
  },
  {
    key: "ai.model.discuss",
    category: "ai",
    tier: "advanced",
    type: "string",
    label: "AI — discuss model id",
    fallback: "",
    env: "AI_MODEL_DISCUSS",
    optionsSource: "nine_router_models",
  },
  {
    key: "ai.model.build",
    category: "ai",
    tier: "advanced",
    type: "string",
    label: "AI — build/edit model id",
    fallback: "",
    env: "AI_MODEL_BUILD",
    optionsSource: "nine_router_models",
  },
  {
    key: "ai.model.vision",
    category: "ai",
    tier: "advanced",
    type: "string",
    label: "AI — vision / image model id",
    fallback: "",
    env: "AI_MODEL_VISION",
    optionsSource: "nine_router_models",
  },
  {
    key: "ai.timeout.discuss_card_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — discuss card timeout (ms)",
    fallback: 45000,
    env: "AI_TIMEOUT_DISCUSS_CARD_MS",
    min: 3000,
    max: 120000,
  },
  {
    key: "ai.timeout.discuss_one_call_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — discuss one-call timeout (ms)",
    fallback: 120000,
    env: "AI_TIMEOUT_DISCUSS_ONE_CALL_MS",
    min: 30000,
    max: 240000,
  },
  {
    key: "ai.timeout.discuss_tool_settle_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — discuss tool settle timeout (ms)",
    fallback: 30000,
    env: "AI_TIMEOUT_DISCUSS_TOOL_SETTLE_MS",
    min: 30000,
    max: 60000,
  },
  {
    key: "ai.timeout.chat_compaction_ms",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — chat compaction timeout (ms)",
    fallback: 60000,
    env: "AI_TIMEOUT_CHAT_COMPACTION_MS",
    min: 30000,
    max: 120000,
  },
  {
    key: "ai.agent.generate_max_steps",
    category: "ai",
    tier: "advanced",
    type: "number",
    label: "AI — generate agent max steps",
    fallback: 40,
    env: "AI_AGENT_GENERATE_MAX_STEPS",
    min: 15,
    max: 60,
  },
];

export function findConfigEntry(key: string): ConfigEntry | undefined {
  return APP_SETTINGS.find((e) => e.key === key);
}
